// 案内所(はじめてのActivityPub)と、ことばの栞の中身。文中のHTMLは自前のもの

export const GUIDE = {
  intro: [
    'フェディバース(fediverse)は、たくさんの小さなSNSサーバが、共通の作法で手紙をやり取りしてつながっている宇宙です。その作法の名前が<b>ActivityPub</b>。MastodonもMisskeyも、この博物街のholloもhackers.pubも、みんな同じ作法を話します。',
    '覚えることばは、まず三つだけでだいじょうぶ。<b>actor</b>(住人ひとりぶんの名刺。あなたのアカウントのこと)、<b>inbox</b>(その人の郵便受け)、<b>outbox</b>(出した手紙の控え)。あとは、歩きながらすこしずつ。',
  ],
  steps: [
    { room: 'hollo-api', title: '書く',
      text: 'スマホのMastodonアプリで「投稿」を押すと、アプリはholloの受付に頼みます——「これを出しておいて」。' },
    { room: 'vocab', title: '共通語に包む',
      text: '投稿は<b>Note</b>という共通語の包みになり、「作りました」という行いは<b>Create</b>という動詞になります。この共通語の辞書が、語彙の経蔵。' },
    { room: 'webfinger', title: '宛先を引く',
      text: 'フォロワーの「@friend@mastodon.social」という宛名から、ほんとうの住所(URL)を電話帳で引きます。それがwebfingerの門。' },
    { room: 'sig', title: '封蝋を捺す',
      text: '手紙に署名を捺します。「ほんとうに本人が出した」「途中で書き換えられていない」を、受け取る側が確かめられるように。' },
    { room: 'kura', title: '船に積む',
      text: '手紙はすぐには投げません。いったん倉(キュー)に預けます——相手の島が留守でも、あとで届け直せるように。' },
    { room: 'sea-route', title: '海を渡る',
      text: '船の正体は、ただのHTTPSのPOSTです。相手のinbox(郵便受け)のURLへ、JSONの手紙を運びます。' },
    { room: 'fedify-honden', title: '相手の島に着く',
      text: '相手の島の本堂が封蝋を検めて、手紙を台帳に写します。フォロワーのタイムラインにあなたの投稿が現れるのは、この写しからです。' },
  ],
  outro: [
    'これが全部です。フェディバースの中身は、宛名の電話帳と、署名つきの手紙と、郵便受け——それを何億通ぶんも丁寧にやるための工夫が、この博物街の部屋々々に納まっています。',
    'むずかしい部屋に入ってしまっても、冒頭の「はじめての人へ」の一行だけ読んで、となりへ進めばだいじょうぶ。地図の右下の<b>レンズ</b>は、最後のお楽しみに——工学の街の床下にある、数学の隠れ街が見えます。',
  ],
};

export const GLOSSARY = [
  { term: 'フェディバース (fediverse)', room: 'sea-route',
    desc: 'ActivityPubでつながったサーバたちの宇宙ぜんぶの呼び名。federation(連合)+universe(宇宙)。' },
  { term: 'ActivityPub', room: 'sea-route',
    desc: '連合SNSの共通の作法(プロトコル)。W3Cの勧告。手紙の書き方と届け方を決めています。' },
  { term: 'actor(アクター)', room: 'fedify-honden',
    desc: '連合宇宙の住人ひとりぶんの名刺。人だけでなく、botやサーバ自身もactorになれます。' },
  { term: 'inbox / outbox', room: 'fedify-honden',
    desc: 'actorごとの郵便受けと、出した手紙の控え。サーバ全体で共有する郵便受け(shared inbox)もあります。' },
  { term: 'Activity', room: 'vocab',
    desc: '「作った(Create)」「フォローした(Follow)」「いいね(Like)」——行いを表す手紙の種類。' },
  { term: 'Note / Article', room: 'vocab',
    desc: '短い投稿がNote、長い記事がArticle。手紙に同封される中身です。' },
  { term: 'JSON-LD', room: 'vocab',
    desc: '手紙の書式。ふつうのJSONに「ことばの意味の辞書(@context)」を添えたもの。' },
  { term: 'WebFinger', room: 'webfinger',
    desc: '「@名前@島」という宛名から住所(URL)を引く、電話帳の仕組み。' },
  { term: 'HTTP署名', room: 'sig',
    desc: '手紙の封蝋。新旧二つの作法(RFC 9421とdraft-cavage)が、いまも両方現役です。' },
  { term: 'Object Integrity Proofs (FEP-8b32)', room: 'sig',
    desc: '封筒ではなく手紙そのものに捺す、新しい印。転送されても検められます。' },
  { term: 'NodeInfo', room: 'nodeinfo',
    desc: 'サーバの自己紹介札。ソフト名、バージョン、住人の数など。' },
  { term: 'リレー', room: 'relay',
    desc: '手紙をまとめて配ってくれる中継所。小さな島どうしをつなぎます。' },
  { term: 'KvStore / MessageQueue', room: 'kura',
    desc: 'fedifyが決めた、棚(保存)と飛脚(配達の待ち行列)の共通の口。postgresでもredisでも同じ形。' },
  { term: 'Mastodon API', room: 'hollo-api',
    desc: 'Mastodonアプリと話すための窓口の形。holloはこれを備えているので、既存アプリがそのまま使えます。' },
  { term: 'fedify', room: 'fedify-honden',
    desc: 'ActivityPubの面倒ごとを引き受けてくれるライブラリ。この博物街の総本山です。' },
];
