// The Visitor Center (ActivityPub for the first time) and the Glossary. The HTML in the text is our own.

export const GUIDE = {
  intro: [
    'The fediverse is a universe where many small social servers connect by exchanging letters under a shared set of manners. The name of those manners is <b>ActivityPub</b>. Mastodon, Misskey, and this museum town\'s hollo and hackers.pub all speak the same manners.',
    'To start, you only need three words. <b>actor</b> (one resident\'s calling card — this is your account), <b>inbox</b> (that person\'s mailbox), and <b>outbox</b> (the file copy of the letters they\'ve sent). The rest you\'ll pick up as you walk.',
  ],
  steps: [
    { room: 'hollo-api', title: 'Write it',
      text: 'When you press "post" in the Mastodon app on your phone, the app asks hollo\'s reception: "Send this out for me."' },
    { room: 'vocab', title: 'Wrap it in the shared tongue',
      text: 'Your post becomes a parcel in the shared tongue called <b>Note</b>, and the act of "I made this" becomes the verb <b>Create</b>. The dictionary of that shared tongue is the Vocabulary Sutra Repository.' },
    { room: 'webfinger', title: 'Look up the address',
      text: 'From a follower\'s address like "@friend@mastodon.social", you look up the real address (its URL) in the directory. That\'s the Webfinger Gate.' },
    { room: 'sig', title: 'Stamp the wax seal',
      text: 'You stamp a signature on the letter — so the receiver can confirm it really was sent by you and wasn\'t altered along the way.' },
    { room: 'kura', title: 'Load it onto the ship',
      text: 'The letter isn\'t thrown out right away. It\'s handed first to a storehouse (a queue) — so that even if the other island is away, it can be redelivered later.' },
    { room: 'sea-route', title: 'Cross the sea',
      text: 'The ship\'s true form is just an HTTPS POST. It carries the JSON letter to the URL of the other party\'s inbox (their mailbox).' },
    { room: 'fedify-honden', title: 'Arrive at the other island',
      text: 'The main hall of the other island examines the wax seal and copies the letter into its ledger. Your post appears on a follower\'s timeline from this copy.' },
  ],
  outro: [
    'That\'s all of it. What\'s inside the fediverse is a directory of addresses, signed letters, and mailboxes — and the craft of doing that carefully, hundreds of millions of times over, is what fills room after room of this museum town.',
    'Even if you wander into a difficult room, you\'ll be fine reading just the one line under "If you\'re new here" and moving on to the next. The <b>lens</b> at the bottom right of the map — save it for last. It reveals the Hidden Town of Mathematics beneath the floor of the engineering town.',
  ],
};

export const GLOSSARY = [
  { term: 'Fediverse', room: 'sea-route',
    desc: 'The name for the whole universe of servers connected by ActivityPub. Federation + universe.' },
  { term: 'ActivityPub', room: 'sea-route',
    desc: 'The shared manners (protocol) of federated social servers. A W3C Recommendation. It sets how letters are written and delivered.' },
  { term: 'Actor', room: 'fedify-honden',
    desc: 'One resident\'s calling card in the federated universe. Not just people — bots and the server itself can be actors too.' },
  { term: 'inbox / outbox', room: 'fedify-honden',
    desc: 'Each actor\'s mailbox, and the file copy of the letters they\'ve sent. There\'s also a mailbox shared by the whole server (the shared inbox).' },
  { term: 'Activity', room: 'vocab',
    desc: '"Created (Create)", "followed (Follow)", "liked (Like)" — the kinds of letters that express an action.' },
  { term: 'Note / Article', room: 'vocab',
    desc: 'A short post is a Note, a long piece is an Article. The contents enclosed with the letter.' },
  { term: 'JSON-LD', room: 'vocab',
    desc: 'The letter\'s format. Ordinary JSON with a "dictionary of word meanings" (@context) added.' },
  { term: 'WebFinger', room: 'webfinger',
    desc: 'The directory mechanism that looks up an address (a URL) from a name like "@name@island".' },
  { term: 'HTTP Signatures', room: 'sig',
    desc: 'The letter\'s wax seal. Two customs, old and new (RFC 9421 and draft-cavage), are both still on duty today.' },
  { term: 'Object Integrity Proofs (FEP-8b32)', room: 'sig',
    desc: 'A new seal, stamped on the letter itself rather than the envelope. It can be verified even after being forwarded.' },
  { term: 'NodeInfo', room: 'nodeinfo',
    desc: 'A server\'s self-introduction placard. Software name, version, number of residents, and so on.' },
  { term: 'Relay', room: 'relay',
    desc: 'A relay station that delivers letters around in bulk. It connects small islands to one another.' },
  { term: 'KvStore / MessageQueue', room: 'kura',
    desc: 'The shared mouths, fixed by fedify, for a shelf (storage) and a courier (a delivery queue). The same shape whether it\'s postgres or redis.' },
  { term: 'Mastodon API', room: 'hollo-api',
    desc: 'The shape of the desk for talking with Mastodon apps. hollo provides this, so existing apps work as they are.' },
  { term: 'fedify', room: 'fedify-honden',
    desc: 'A library that takes ActivityPub\'s troublesome parts off your hands. The head temple of this museum town.' },
];
