// 안내소(처음 만나는 ActivityPub)와, 낱말 갈피의 내용. 본문의 HTML은 자체 태그예요

export const GUIDE = {
  intro: [
    '페디버스(fediverse)는 자그마한 SNS 서버가 많이 모여, 공통의 작법으로 편지를 주고받으며 이어진 우주예요. 그 작법의 이름이 <b>ActivityPub</b>예요. Mastodon도 Misskey도, 이 박물관 거리의 hollo와 hackers.pub도, 모두 같은 작법으로 이야기해요.',
    '외울 낱말은 우선 세 가지면 충분해요. <b>actor</b>(주민 한 사람의 명함. 내 계정을 말해요), <b>inbox</b>(그 사람의 우편함), <b>outbox</b>(부친 편지의 사본)예요. 나머지는 걸으면서 조금씩 익히면 돼요.',
  ],
  steps: [
    { room: 'hollo-api', title: '쓰기',
      text: '스마트폰 Mastodon 앱에서 "게시"를 누르면, 앱은 hollo 접수처에 부탁해요 — "이걸 부쳐 줘".' },
    { room: 'vocab', title: '공통어로 감싸기',
      text: '게시물은 <b>Note</b>라는 공통어 꾸러미가 되고, "만들었어요"라는 행위는 <b>Create</b>라는 동사가 돼요. 이 공통어 사전이 어휘의 장경각이에요.' },
    { room: 'webfinger', title: '수신처 찾기',
      text: '팔로워의 "@friend@mastodon.social"이라는 이름에서 진짜 주소(URL)를 전화번호부로 찾아요. 그게 webfinger의 문이에요.' },
    { room: 'sig', title: '봉랍 찍기',
      text: '편지에 서명을 찍어요. "정말 본인이 부쳤다", "도중에 고쳐지지 않았다"를 받는 쪽이 확인할 수 있도록요.' },
    { room: 'kura', title: '배에 싣기',
      text: '편지를 바로 던지지 않아요. 일단 곳간(큐)에 맡겨요 — 상대 섬이 비어 있어도 나중에 다시 보낼 수 있도록요.' },
    { room: 'sea-route', title: '바다 건너기',
      text: '배의 정체는 그냥 HTTPS POST예요. 상대의 inbox(우편함) URL로 JSON 편지를 날라요.' },
    { room: 'fedify-honden', title: '상대 섬에 닿기',
      text: '상대 섬의 본당이 봉랍을 살펴본 뒤 편지를 장부에 옮겨 적어요. 팔로워 타임라인에 내 게시물이 나타나는 건 이 사본에서예요.' },
  ],
  outro: [
    '이게 전부예요. 페디버스의 속은 수신처 전화번호부, 서명이 붙은 편지, 그리고 우편함 — 이것을 수억 통이나 정성껏 해내기 위한 궁리가 이 박물관 거리의 방 곳곳에 담겨 있어요.',
    '어려운 방에 들어가더라도, 맨 앞의 "처음 오신 분께" 한 줄만 읽고 옆으로 가면 돼요. 지도 오른쪽 아래의 <b>렌즈</b>는 맨 마지막 즐거움으로 남겨 두세요 — 공학 거리 마룻바닥 아래에 있는, 수학의 숨은 거리가 보여요.',
  ],
};

export const GLOSSARY = [
  { term: '페디버스 (fediverse)', room: 'sea-route',
    desc: 'ActivityPub로 이어진 서버가 이룬 우주 전체를 부르는 이름이에요. federation(연합)+universe(우주)를 합친 말이에요.' },
  { term: 'ActivityPub', room: 'sea-route',
    desc: '연합 SNS의 공통 작법(프로토콜)이에요. W3C 권고예요. 편지 쓰는 법과 보내는 법을 정해 두었어요.' },
  { term: 'actor(액터)', room: 'fedify-honden',
    desc: '연합 우주 주민 한 사람의 명함이에요. 사람뿐 아니라 봇이나 서버 자신도 actor가 될 수 있어요.' },
  { term: 'inbox / outbox', room: 'fedify-honden',
    desc: 'actor마다 있는 우편함과, 부친 편지의 사본이에요. 서버 전체가 함께 쓰는 우편함(shared inbox)도 있어요.' },
  { term: 'Activity', room: 'vocab',
    desc: '"만들었다(Create)", "팔로우했다(Follow)", "좋아요(Like)" — 행위를 나타내는 편지의 종류예요.' },
  { term: 'Note / Article', room: 'vocab',
    desc: '짧은 게시물이 Note, 긴 글이 Article이에요. 편지에 함께 넣는 알맹이예요.' },
  { term: 'JSON-LD', room: 'vocab',
    desc: '편지의 서식이에요. 평범한 JSON에 "낱말 뜻 사전(@context)"을 곁들인 거예요.' },
  { term: 'WebFinger', room: 'webfinger',
    desc: '"@이름@섬"이라는 이름에서 주소(URL)를 찾는 전화번호부 장치예요.' },
  { term: 'HTTP 서명', room: 'sig',
    desc: '편지의 봉랍이에요. 새것과 옛것 두 가지 작법(RFC 9421과 draft-cavage)이 지금도 둘 다 현역이에요.' },
  { term: 'Object Integrity Proofs (FEP-8b32)', room: 'sig',
    desc: '봉투가 아니라 편지 자체에 찍는 새로운 도장이에요. 전달돼도 확인할 수 있어요.' },
  { term: 'NodeInfo', room: 'nodeinfo',
    desc: '서버의 자기소개 팻말이에요. 소프트웨어 이름, 버전, 주민 수 같은 것들이에요.' },
  { term: '릴레이', room: 'relay',
    desc: '편지를 한꺼번에 돌려 주는 중계소예요. 작은 섬끼리 이어 줘요.' },
  { term: 'KvStore / MessageQueue', room: 'kura',
    desc: 'fedify가 정한, 선반(저장)과 파발(배달 대기열)의 공통 창구예요. postgres든 redis든 같은 모양이에요.' },
  { term: 'Mastodon API', room: 'hollo-api',
    desc: 'Mastodon 앱과 이야기하기 위한 창구의 모양이에요. hollo는 이걸 갖추고 있어서 기존 앱을 그대로 쓸 수 있어요.' },
  { term: 'fedify', room: 'fedify-honden',
    desc: 'ActivityPub의 번거로운 일을 도맡아 주는 라이브러리예요. 이 박물관 거리의 총본산이에요.' },
];
