// 지도 표찰의 문구(한국어)
const GH_F = 'https://github.com/fedify-dev/fedify/tree/main/';
const GH_H = 'https://github.com/fedify-dev/hollo/tree/main/';
const GH_P = 'https://github.com/hackers-pub/hackerspub/tree/main/';

export const CAPTIONS = {
  welcome: { kind: '안내', name: '페디 박물거리에 오신 걸 환영해요',
    body: 'fedify · hollo · hackers.pub, 이 세 가지 오픈소스를 걸어서 둘러보는 박물거리로 꾸민 페이지예요. 지도는 손가락으로 집어서 움직이고, 표시를 누르면 가까이 다가가요. 하얀 작은 동그라미는 아직 안 본 전시예요. 한 번 보면 붉은 도장으로 바뀌어요. 처음 오신 분은 문 옆의 "안내소"에서 시작하면 돼요. 밤이 되는 렌즈는 맨 마지막 즐거움으로 남겨 두세요.',
    links: [['처음 만나는 ActivityPub(안내소)', '/section/fedify/rooms/guide/'], ['낱말 갈피', '/section/fedify/rooms/kotoba/']] },
  guide: { kind: '안내', name: '안내소',
    body: 'ActivityPub가 처음이신 분은 여기에서 시작하세요. 편지 한 통이 바다를 건너기까지를, 일곱 개의 방을 따라 안내해요. 낱말이 헷갈릴 때 펴 보는 갈피도 놓여 있어요.',
    links: [['낱말 갈피', '/section/fedify/rooms/kotoba/']] },
  'fedify-honden': { kind: 'fedify 본섬 · 본당', name: '연합의 방',
    body: 'fedify의 심장부예요. Federation 객체가 여기 앉아서, inbox로 들어온 문서를 받고, outbox에서 부치고, 액터 장부를 모두 도맡아 처리해요. hollo도 hackers.pub도 이 배치를 그대로 자기 건물에 옮겨 놓았어요.',
    links: [['이 방을 GitHub에서 보기', GH_F + 'packages/fedify/src/federation']] },
  sig: { kind: 'fedify 본섬', name: '의전의 방',
    body: '문서에 도장을 찍고, 들어온 도장을 살펴보는 방이에요. HTTP Message Signatures(RFC 9421)와 예전의 draft-cavage, 이 두 가지 작법을 상대에 맞춰 골라 써요(double-knock). FEP-8b32의 Object Integrity Proofs도 여기 있어요. 렌즈를 쓰면 이 방 마룻바닥 아래로 실이 보여요.',
    links: [['이 방을 GitHub에서 보기', GH_F + 'packages/fedify/src/sig']] },
  vocab: { kind: 'fedify 본섬', name: '어휘의 장경각',
    body: 'Note, Follow, Like…… ActivityStreams의 어휘가 TypeScript 타입으로 한 낱말씩 경문이 되어 담긴 장경각이에요. 사경은 손이 아니라 코드 생성으로, Activity Vocabulary 명세에서 한 자씩 옮겨 적어요.',
    links: [['이 장경각을 GitHub에서 보기', GH_F + 'packages/vocab']] },
  webfinger: { kind: 'fedify 본섬 · 첫 번째 문', name: 'webfinger의 문',
    body: '섬의 첫 번째 문이에요. "@handle@host"라는 이름에서 actor의 주소(URL)를 찾아요. 연합 우주에서 누군가를 찾아가는 여정은 언제나 이 문을 지나면서 시작돼요.',
    links: [['이 문을 GitHub에서 보기', GH_F + 'packages/webfinger']] },
  nodeinfo: { kind: 'fedify 본섬', name: 'nodeinfo 알림판',
    body: '"이 서버는 무엇이고 주민은 몇 명인지"를 적어서 내거는 알림판이에요. 다른 섬의 통계청이 이따금 읽으러 와요.',
    links: [['이 알림판을 GitHub에서 보기', GH_F + 'packages/fedify/src/nodeinfo']] },
  kura: { kind: 'fedify 본섬', name: '곳간 구역',
    body: 'postgres · redis · sqlite · mysql · denokv 곳간과, amqp 파발 오두막이에요. fedify는 KvStore와 MessageQueue라는 같은 모양의 창구를 정해 두어서, 어느 곳간을 이어도 본전은 같은 얼굴로 움직여요.',
    links: [['곳간들을 GitHub에서 보기', GH_F + 'packages']] },
  kobo: { kind: 'fedify 본섬', name: '연장 공방',
    body: 'fedify CLI와 debugger 공방이에요. init으로 새 섬의 터를 잡고, lookup으로 다른 섬의 actor를 조회하고, debugger로 들어온 문서의 속을 들여다봐요. 나그네(개발자)를 위한 연장 가게예요.',
    links: [['CLI 공방', GH_F + 'packages/cli'], ['debugger 선반', GH_F + 'packages/debugger']] },
  bridges: { kind: 'fedify 본섬 · 동쪽 기슭', name: '열네 개의 다리',
    body: 'hono, express, fastify, koa, h3, elysia, nestjs, next, nuxt, sveltekit, fresh, astro, solidstart, cfworkers. 어느 프레임워크의 기슭에도 같은 모양의 다리가 놓여요. hollo는 hono 다리를 건너 본섬에 닿아요.',
    links: [['다리 목록을 GitHub에서 보기', GH_F + 'packages']] },
  relay: { kind: '앞바다 바위', name: 'relay 등대',
    body: '일대일로 편지를 주고받는 대신, 등대가 한꺼번에 맡아서 돌려 보내는 중계소예요. 작은 섬끼리 등대를 사이에 두고 이어져요.',
    links: [['이 등대를 GitHub에서 보기', GH_F + 'packages/relay']] },
  'sea-route': { kind: '외교의 바다', name: '외교 항로',
    body: 'ActivityPub라는 공통의 의전으로 쓰인 외교 문서(Activity)가 배로 오가는 바다예요. 목적지는 마스토돈 대륙, 미스키 군도, 그 너머의 수많은 섬들이에요. 배가 나르는 건 JSON-LD, 봉랍은 HTTP 서명이에요.',
    links: [['의전 원문(W3C 권고)', 'https://www.w3.org/TR/activitypub/']] },
  'hollo-pages': { kind: 'hollo 관 · 3층', name: '사랑방',
    body: '현관 앞의 공개 프로필과 게시물 페이지예요. 찾아온 사람이 맨 처음 안내받는 곳이에요.',
    links: [['이 층을 GitHub에서 보기', GH_H + 'src/pages']] },
  'hollo-api': { kind: 'hollo 관 · 2층', name: '접수처(Mastodon API)',
    body: 'v1/v2 창구예요. 쓰던 Mastodon 앱이 여기에 말을 걸면 hollo가 안에서 모두 번역해요. 그래서 옮겨 와도 늘 쓰던 앱 그대로 지낼 수 있어요.',
    links: [['이 층을 GitHub에서 보기', GH_H + 'src/api']] },
  'hollo-fed': { kind: 'hollo 관 · 1층', name: '외교실',
    body: 'fedify 별원이 상주하면서, 바깥 우주와의 편지 왕래를 모두 맡아 주는 방이에요. 들어온 문서는 여기에서 살펴본 뒤 건물 장부에 옮겨 적어요.',
    links: [['이 층을 GitHub에서 보기', GH_H + 'src/federation']] },
  'hollo-oauth': { kind: 'hollo 관 · 별채', name: '열쇠의 방',
    body: '앱에 여벌 열쇠(토큰)를 만들어 건네주는 별채예요. 여벌 열쇠가 없으면 접수처가 연결해 주지 않아요.',
    links: [['이 별채를 GitHub에서 보기', GH_H + 'src/oauth']] },
  'hollo-bunsha': { kind: 'hollo 경내 · 별원', name: 'fedify 별원(npm 판본)',
    body: 'npm 판본에서 사경했어요, ^2.3.0. node_modules에 사본으로 담겨 있는데도, 아무도 그저 복제라고 부르지 않아요 — 같은 경이 여기에서 살아 읽히고 있으니까요. 불을 나눠도 본래의 불은 줄지 않아요. 총본산과 같은 경문인지, 확인하러 가 봐도 좋아요.',
    links: [['총본산(fedify 본섬)으로', 'https://github.com/fedify-dev/fedify'],
      ['npm 판본 목록', 'https://www.npmjs.com/package/@fedify/fedify']] },
  'hp-web': { kind: 'hackers.pub 관', name: '열람실(web)',
    body: 'Fresh의 routes와 islands예요. "섬(islands)"이라는 말이 이 건물에서는 건축 용어예요. 읽는 사람을 위한, 가장 큰 방이에요.',
    links: [['이 동을 GitHub에서 보기', GH_P + 'web']] },
  'hp-graphql': { kind: 'hackers.pub 관', name: '조회실(graphql)',
    body: '다음 건물(web-next)을 위한 GraphQL 창구예요. 물어볼 것을 종이 한 장(query)에 적어서 내면, 필요한 만큼만 돌아와요.',
    links: [['이 동을 GitHub에서 보기', GH_P + 'graphql']] },
  'hp-models': { kind: 'hackers.pub 관', name: '서고(models)',
    body: '도메인 모델 서고예요. 건물 곳곳의 동이 이곳 장부를 함께 써요.',
    links: [['이 동을 GitHub에서 보기', GH_P + 'models']] },
  'hp-fed': { kind: 'hackers.pub 관', name: '외교실(federation)',
    body: 'inbox로 온 문서를 fedify 별원이 살펴본 뒤 장부에 옮겨 적는 방이에요. hollo의 외교실과 같은 배치예요 — 같은 경으로 지었으니까요.',
    links: [['이 동을 GitHub에서 보기', GH_P + 'federation']] },
  'hp-ai': { kind: 'hackers.pub 관', name: '신관(ai)',
    body: 'AI 실험동이에요. 아직 증축 중인 냄새가 나요.',
    links: [['이 동을 GitHub에서 보기', GH_P + 'ai']] },
  'hp-bunsha': { kind: 'hackers.pub 경내 · 별원', name: 'fedify 별원(JSR 판본)',
    body: '이쪽은 JSR 판본에서 사경했어요, 2.3.1. hollo의 별원과 판목이 다른데도 경의 내용은 같아요. 버전 숫자는 옮겨 적은 연호 같은 거예요. 대장경에 고려장이나 가흥장이 있었듯이, 같은 정전에 판본이 여럿 있는 거죠.',
    links: [['총본산(fedify 본섬)으로', 'https://github.com/fedify-dev/fedify'],
      ['JSR 판본 목록', 'https://jsr.io/@fedify/fedify']] },
  'math-ec': { kind: '수학의 숨은 거리', name: '타원곡선 공방',
    body: 'Ed25519예요. Curve25519라는 곡선 위에서 점을 더하면 위조할 수 없는 도장이 만들어져요. 의전의 방에서 찍는 서명은 마룻바닥 아래 이 공방에서 찍혀요. 쓰기만 할 거라면 몰라도 돼요. 알고 있으면 도장이 비쳐 보여요.',
    links: [['마룻바닥 위 의전의 방', GH_F + 'packages/fedify/src/sig']] },
  'math-prime': { kind: '수학의 숨은 거리', name: '소수의 우물',
    body: 'RSA예요. 큰 소수 두 개를 곱하는 건 한순간, 곱한 값에서 되나누는 건 천 년이에요. 우물은 깊은 쪽으로 떨어지기는 쉬워도 오르기는 어려워요. 오래된 우물이지만 아직 현역이에요.',
    links: [] },
  'math-hash': { kind: '수학의 숨은 거리', name: '일방통행 문',
    body: 'SHA-256이에요. 아무리 긴 문서라도 이 문을 지나면 32바이트 그림자가 돼요. 그림자에서 문서로는 되돌아갈 수 없어요. 문서가 한 글자만 달라도 그림자는 아주 딴판이에요. 외교 문서의 digest는 이 문의 도장이에요.',
    links: [] },
  'math-graph': { kind: '수학의 숨은 거리', name: '그래프 서고',
    body: 'JSON-LD의 정규화(RDF Dataset Canonicalization)예요. "쓴 방식만 다를 뿐 뜻은 같은 문서"에 같은 이름을 붙이려고, 그래프에 정규 라벨을 매겨요. 수수한 얼굴을 하고 있지만 꽤 깊은 문제예요.',
    links: [] },
  'math-logic': { kind: '수학의 숨은 거리', name: '논리의 신전',
    body: 'TypeScript 타입이에요. Curry–Howard 대응으로 말하면, 타입 검사가 통과한다는 건 작은 증명이 통과한다는 거죠. 어휘의 장경각에 담긴 낱말 하나하나가 이 신전에서 뒷받침돼요.',
    links: [] },
};
