// Map caption texts (English)
const GH_F = 'https://github.com/fedify-dev/fedify/tree/main/';
const GH_H = 'https://github.com/fedify-dev/hollo/tree/main/';
const GH_P = 'https://github.com/hackers-pub/hackerspub/tree/main/';

export const CAPTIONS = {
  welcome: { kind: 'Information', name: 'Welcome to the Fedi Museum Town',
    body: 'This page turns three open-source projects — fedify, hollo, and hackers.pub — into a museum town you can walk through. Pinch and drag the map; tap a marker to draw closer. A small white dot is an exhibit you haven\'t seen yet; once you do, it turns to a vermilion stamp. New here? Start at the Visitor Center by the gate. Save the lens that brings on nightfall for last — it\'s the best surprise.',
    links: [['ActivityPub for the first time (Visitor Center)', '/section/fedify/rooms/guide/'], ['Glossary', '/section/fedify/rooms/kotoba/']] },
  guide: { kind: 'Information', name: 'Visitor Center',
    body: 'New to ActivityPub? Start right here. We\'ll follow a single letter room by room, across seven rooms, until it crosses the sea. A glossary waits here too, for whenever a word trips you up.',
    links: [['Glossary', '/section/fedify/rooms/kotoba/']] },
  'fedify-honden': { kind: 'fedify Main Island · Main Hall', name: 'The Federation Chamber',
    body: 'The heart of fedify. The Federation object is seated here, and it directs everything: receiving documents at the inbox, dispatching from the outbox, keeping the ledger of actors. Both hollo and hackers.pub copy this same floor plan straight into their own halls.',
    links: [['See this chamber on GitHub', GH_F + 'packages/fedify/src/federation']] },
  sig: { kind: 'fedify Main Island', name: 'The Chamber of Rites',
    body: 'The room where documents are sealed and arriving seals are examined. It handles two customs and matches the one your correspondent uses — HTTP Message Signatures (RFC 9421) and the older draft-cavage (double-knock). FEP-8b32\'s Object Integrity Proofs live here too. Put on the lens and you\'ll see threads running beneath this floor.',
    links: [['See this chamber on GitHub', GH_F + 'packages/fedify/src/sig']] },
  vocab: { kind: 'fedify Main Island', name: 'The Vocabulary Sutra Repository',
    body: 'Note, Follow, Like… the ActivityStreams vocabulary is enshrined here, each word copied out as a TypeScript type like a passage of scripture. The copying is done not by hand but by code generation, transcribed word for word from the Activity Vocabulary spec.',
    links: [['See this repository on GitHub', GH_F + 'packages/vocab']] },
  webfinger: { kind: 'fedify Main Island · First Gate', name: 'The Webfinger Gate',
    body: 'The island\'s first gate. From a name like "@handle@host", it looks up an actor\'s address (its URL). Every journey to visit someone across the federated universe begins by passing through this gate.',
    links: [['See this gate on GitHub', GH_F + 'packages/webfinger']] },
  nodeinfo: { kind: 'fedify Main Island', name: 'The Nodeinfo Notice Board',
    body: 'A notice board that posts who this server is and how many people live here. Statistics offices from other islands stop by to read it now and then.',
    links: [['See this notice board on GitHub', GH_F + 'packages/fedify/src/nodeinfo']] },
  kura: { kind: 'fedify Main Island', name: 'The Storehouse Quarter',
    body: 'Storehouses for postgres, redis, sqlite, mysql, and denokv, plus a courier hut for amqp. fedify fixes one shape for the mouth of each — KvStore and MessageQueue — so whichever storehouse you connect, the main hall runs with the same face.',
    links: [['See the row of storehouses on GitHub', GH_F + 'packages']] },
  kobo: { kind: 'fedify Main Island', name: 'The Toolmaker\'s Workshop',
    body: 'The workshop for the fedify CLI and debugger. Use init to stake out a new island\'s bounds, lookup to query another actor, and the debugger to peer inside a document that arrived. A tool shop for travelers — that is, developers.',
    links: [['The CLI workshop', GH_F + 'packages/cli'], ['The debugger shelf', GH_F + 'packages/debugger']] },
  bridges: { kind: 'fedify Main Island · East Shore', name: 'The Fourteen Bridges',
    body: 'hono, express, fastify, koa, h3, elysia, nestjs, next, nuxt, sveltekit, fresh, astro, solidstart, cfworkers. To every framework\'s shore, a bridge of the same shape is thrown across. hollo crosses the hono bridge to reach the main island.',
    links: [['See the list of bridges on GitHub', GH_F + 'packages']] },
  relay: { kind: 'Offshore Rock', name: 'The Relay Lighthouse',
    body: 'Instead of writing one-to-one, the lighthouse takes letters in all at once and hands them back around — a relay station. Small islands connect to one another across the lighthouse\'s beam.',
    links: [['See this lighthouse on GitHub', GH_F + 'packages/relay']] },
  'sea-route': { kind: 'Sea of Diplomacy', name: 'The Diplomatic Sea Lanes',
    body: 'The sea where diplomatic documents (Activities), written in the shared rite called ActivityPub, sail back and forth. Their destinations: the continent of Mastodon, the Misskey archipelago, and countless islands beyond. What the ships carry is JSON-LD; the wax seal is an HTTP signature.',
    links: [['The rite in the original (W3C Recommendation)', 'https://www.w3.org/TR/activitypub/']] },
  'hollo-pages': { kind: 'Hollo Hall · 3F', name: 'The Parlor',
    body: 'The public profile and post pages at the doorstep. Where a visitor is first shown in.',
    links: [['See this floor on GitHub', GH_H + 'src/pages']] },
  'hollo-api': { kind: 'Hollo Hall · 2F', name: 'Reception (Mastodon API)',
    body: 'The v1/v2 desk. When your usual Mastodon app speaks here, hollo translates all of it behind the counter. So even after you move in, you can keep living with the same app you always used.',
    links: [['See this floor on GitHub', GH_H + 'src/api']] },
  'hollo-fed': { kind: 'Hollo Hall · 1F', name: 'The Diplomacy Office',
    body: 'The room that keeps a fedify branch temple in residence and leaves all correspondence with the outer universe to it. Documents that arrive are examined here and copied into the hall\'s ledger.',
    links: [['See this floor on GitHub', GH_H + 'src/federation']] },
  'hollo-oauth': { kind: 'Hollo Hall · Annex', name: 'The Key Room',
    body: 'The annex that cuts a spare key (a token) for each app and hands it over. Without the spare key, reception won\'t pass your message along.',
    links: [['See this annex on GitHub', GH_H + 'src/oauth']] },
  'hollo-bunsha': { kind: 'Hollo Grounds · Branch Temple', name: 'Fedify Branch Temple (npm edition)',
    body: 'Copied from the npm edition, ^2.3.0. It sits in node_modules as a transcript, yet no one calls it a mere duplicate — the same scripture is read here, alive. Sharing a flame doesn\'t dim the original fire. You\'re welcome to go and confirm it\'s the very same text as the head temple.',
    links: [['To the head temple (fedify Main Island)', 'https://github.com/fedify-dev/fedify'],
      ['The npm edition\'s catalog', 'https://www.npmjs.com/package/@fedify/fedify']] },
  'hp-web': { kind: 'hackers.pub Hall', name: 'The Reading Room (web)',
    body: 'Fresh\'s routes and islands. In this hall, "islands" is an architectural term. The largest room of all — the one for readers.',
    links: [['See this wing on GitHub', GH_P + 'web']] },
  'hp-graphql': { kind: 'hackers.pub Hall', name: 'The Inquiry Room (graphql)',
    body: 'The GraphQL desk for the next hall (web-next). Write your request on a single sheet (a query) and hand it in, and you get back exactly as much as you asked for.',
    links: [['See this wing on GitHub', GH_P + 'graphql']] },
  'hp-models': { kind: 'hackers.pub Hall', name: 'The Stacks (models)',
    body: 'The stacks for the domain models. Every wing in the hall shares the ledger kept here.',
    links: [['See this wing on GitHub', GH_P + 'models']] },
  'hp-fed': { kind: 'hackers.pub Hall', name: 'The Diplomacy Office (federation)',
    body: 'The room where a fedify branch temple examines documents bound for the inbox before copying them into the ledger. It has the same floor plan as hollo\'s diplomacy office — because both are built from the same scripture.',
    links: [['See this wing on GitHub', GH_P + 'federation']] },
  'hp-ai': { kind: 'hackers.pub Hall', name: 'The New Wing (ai)',
    body: 'The experimental wing for AI. It still smells of fresh construction.',
    links: [['See this wing on GitHub', GH_P + 'ai']] },
  'hp-bunsha': { kind: 'hackers.pub Grounds · Branch Temple', name: 'Fedify Branch Temple (JSR edition)',
    body: 'This one is copied from the JSR edition, 2.3.1. Its printing blocks differ from hollo\'s branch temple, yet the scripture inside is the same. The version number is like the era name of the year it was transcribed. Just as the Buddhist canon had a Goryeo edition and a Jiaxing edition, one true canon can have several editions.',
    links: [['To the head temple (fedify Main Island)', 'https://github.com/fedify-dev/fedify'],
      ['The JSR edition\'s catalog', 'https://jsr.io/@fedify/fedify']] },
  'math-ec': { kind: 'Hidden Town of Mathematics', name: 'The Elliptic Curve Atelier',
    body: 'Ed25519. Add points together on the curve called Curve25519, and you get a seal no one can forge. The signatures in the Chamber of Rites are stamped down here, in this atelier beneath the floor. You don\'t need to know it to use it. Know it, and you can see through the seal.',
    links: [['The Chamber of Rites above the floor', GH_F + 'packages/fedify/src/sig']] },
  'math-prime': { kind: 'Hidden Town of Mathematics', name: 'The Well of Primes',
    body: 'RSA. Multiplying two large primes takes an instant; dividing the product back out takes a thousand years. A well is easy to fall down into, hard to climb back up. An old well, but still on duty.',
    links: [] },
  'math-hash': { kind: 'Hidden Town of Mathematics', name: 'The One-Way Door',
    body: 'SHA-256. A document of any length, passing through this door, becomes a 32-byte shadow. From the shadow back to the document, there is no return. Change one character in the document and the shadow is something else entirely. A diplomatic document\'s digest is this door\'s seal.',
    links: [] },
  'math-graph': { kind: 'Hidden Town of Mathematics', name: 'The Graph Archive',
    body: 'JSON-LD canonicalization (RDF Dataset Canonicalization). To give "the same document written differently, meaning the same thing" a single name, it assigns canonical labels across the graph. A plain-looking face over a surprisingly deep problem.',
    links: [] },
  'math-logic': { kind: 'Hidden Town of Mathematics', name: 'The Temple of Logic',
    body: 'TypeScript\'s types. In terms of the Curry–Howard correspondence, passing the type check is passing a small proof. Every single word in the Vocabulary Sutra Repository is endorsed here, in this temple.',
    links: [] },
};
